name: Deploy Shiny

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:

  deploy:
    uses: ./.github/workflows/deploy_inference_env.yml
    if: github.ref == 'refs/heads/main'
    with:
      short_name: sgs-shiny
      environment: prd
      resource_group: {{ cookiecutter.dev_rg }}
      acr_name: sgsshinyprdcreg
      vm_size: B1
      build_number: ${{ github.run_number }}
      
    secrets:
      azure_credentials: {{ "${{" }} secrets.{{cookiecutter.service_principal_name}} {{ "}}" }}
      subscription_id: {{  "${{" }} secrets.{{ cookiecutter.subscription_id_name }} {{ "}}"  }}
