name: Deploy Shiny app - test

concurrency: deploy-test

env:
  ENVIRONMENT: test
  RESOURCE_GROUP: shiny-test-rg
  ACR_NAME: shinytestcr
  SHORT_NAME: shinyapp
  VM_SIZE: B1
  KV_NAME: shiny-test-kv
  KV_ACCESS: true

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:

  vars:
    runs-on: ubuntu-latest
    outputs:
      resource_group: ${{ env.RESOURCE_GROUP }}
      acr_name: ${{ env.ACR_NAME }}
      short_name: ${{ env.SHORT_NAME }}
      kv_name: ${{ env.KV_NAME }}
      environment: ${{ env.ENVIRONMENT }}
      kv_access: ${{ env.KV_ACCESS }}
      vm_size: ${{ env.VM_SIZE }}
    steps:
      - run: echo "Exposing env vars"

  deploy:
    needs: vars
    uses: ./.github/workflows/deploy_reusable.yml
    if: github.ref == 'refs/heads/main'
    with:
      short_name: ${{ needs.vars.outputs.short_name }}
      environment: ${{ needs.vars.outputs.environment }}
      resource_group: ${{ needs.vars.outputs.resource_group }}
      acr_name: ${{ needs.vars.outputs.acr_name }}
      vm_size: ${{ needs.vars.outputs.vm_size }}
      build_number: ${{ github.run_number }}
      
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      subscription_id: ${{ secrets.SUBSCRIPTION_ID }}

  kv-access:
    needs: [vars, deploy]
    uses: ./.github/workflows/kv_access.yml
    if: ${{ needs.vars.outputs.kv_access}} == true #github.ref == 'refs/heads/main' && 
    with:
      environment: ${{ needs.vars.outputs.environment }}
      resource_group: ${{ needs.vars.outputs.resource_group }}
      kv_name: ${{ needs.vars.outputs.kv_name }}
      webapp_name: ${{ needs.vars.outputs.short_name }}-${{ needs.vars.outputs.environment }}-wa
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
