name: Key vault access

on:
  workflow_call:
    inputs:
      resource_group:
        required: true
        type: string
      environment:
        required: true
        type: string
      webapp_name:
        required: true
        type: string
      kv_name:
        required: true
        type: string     
    secrets:
      azure_credentials:
        required: true

jobs:
  access-to-kv:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}
        
        # Assign identity  
      - run: |
          az webapp identity assign -g ${{ inputs.resource_group }} -n ${{ inputs.webapp_name }}

        # get SP ID
      - run: |
          export spID=$(az webapp show \
            --resource-group ${{ inputs.resource_group }}  \
            --name ${{ inputs.webapp_name }} \
            --query identity.principalId --out tsv)
          echo "sp_id=$spID" >> $GITHUB_OUTPUT
        name: 'Get Service Principal (obj id)'
        id: get_sp_step
        
        # set kv policy
      - run: |
          az keyvault set-policy \
            --name ${{ inputs.kv_name }} \
            --resource-group ${{ inputs.resource_group }}  \
            --object-id ${{ steps.get_sp_step.outputs.sp_id }} \
            --secret-permissions get
            
    outputs:
      sp_id: ${{ steps.get_sp_step.outputs.rg_id_step.sp_id }}



#az config set extension.use_dynamic_install=yes_without_prompt
#az webapp auth microsoft show --name shinyapp-test-wa --resource-group shiny-test-rg